
/**
 * 页面跳转路由管理
 */
export class PAGE_PATH {
  /**根组件在导航栏唯一标识*/
  static readonly MAIN_PAGE: string = "mainNavigation"
  /**启动页*/
  static readonly LAUNCH_PAGE: string = "launchPage"
  /**主页面*/
  static readonly HOME_PAGE: string = "homePage"

  /**主页面*/
  static readonly FEATURE_BOOKSHELF_PAGE: string = "bookShelfPage"
  /**主页面*/
  static readonly FEATURE_CALENDER_PAGE: string = "calenderPage"
  /**主页面*/
  static readonly FEATURE_JOURNAL_PAGE: string = "journalPage"
  /**主页面*/
  static readonly FEATURE_ME_PAGE: string = "mePage"
}